-[09-May-22 00:54:27] INFO - Started server process [293082]
[09-May-22 00:54:27] INFO - Waiting for application startup.
[09-May-22 00:54:27] INFO - Application startup complete.
[09-May-22 00:56:39] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 77, in add_place
    result = session.add(salesmen(id_player=data.id_player,
AttributeError: 'dict' object has no attribute 'id_player'
[09-May-22 00:57:02] INFO - Shutting down
[09-May-22 00:57:02] INFO - Waiting for application shutdown.
[09-May-22 00:57:02] INFO - Application shutdown complete.
[09-May-22 00:57:02] INFO - Finished server process [293082]
[09-May-22 00:57:03] INFO - Started server process [293297]
[09-May-22 00:57:03] INFO - Waiting for application startup.
[09-May-22 00:57:03] INFO - Application startup complete.
[09-May-22 00:58:55] INFO - Started server process [293704]
[09-May-22 00:58:55] INFO - Waiting for application startup.
[09-May-22 00:58:55] INFO - Application startup complete.
[09-May-22 00:58:59] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 79, in add_place
    result = session.add(salesmen(id_player=data.id_player,
AttributeError: 'dict' object has no attribute 'id_player'
[09-May-22 00:59:00] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 79, in add_place
    result = session.add(salesmen(id_player=data.id_player,
AttributeError: 'dict' object has no attribute 'id_player'
[09-May-22 01:01:14] INFO - Shutting down
[09-May-22 01:01:14] INFO - Waiting for application shutdown.
[09-May-22 01:01:14] INFO - Application shutdown complete.
[09-May-22 01:01:14] INFO - Finished server process [293704]
[09-May-22 01:01:15] INFO - Started server process [293885]
[09-May-22 01:01:15] INFO - Waiting for application startup.
[09-May-22 01:01:15] INFO - Application startup complete.
[09-May-22 01:02:55] INFO - Shutting down
[09-May-22 01:02:55] INFO - Waiting for application shutdown.
[09-May-22 01:02:55] INFO - Application shutdown complete.
[09-May-22 01:02:55] INFO - Finished server process [293885]
[09-May-22 01:02:56] INFO - Started server process [294037]
[09-May-22 01:02:56] INFO - Waiting for application startup.
[09-May-22 01:02:56] INFO - Application startup complete.
[09-May-22 01:04:04] INFO - Shutting down
[09-May-22 01:04:04] INFO - Waiting for application shutdown.
[09-May-22 01:04:04] INFO - Application shutdown complete.
[09-May-22 01:04:04] INFO - Finished server process [294037]
[09-May-22 01:08:26] INFO - Started server process [294233]
[09-May-22 01:08:26] INFO - Waiting for application startup.
[09-May-22 01:08:26] INFO - Application startup complete.
[09-May-22 01:12:48] INFO - Shutting down
[09-May-22 01:12:48] INFO - Waiting for application shutdown.
[09-May-22 01:12:48] INFO - Application shutdown complete.
[09-May-22 01:12:48] INFO - Finished server process [294233]
[09-May-22 01:12:49] INFO - Started server process [294438]
[09-May-22 01:12:49] INFO - Waiting for application startup.
[09-May-22 01:12:49] INFO - Application startup complete.
[09-May-22 01:12:52] INFO - Shutting down
[09-May-22 01:12:52] INFO - Waiting for application shutdown.
[09-May-22 01:12:52] INFO - Application shutdown complete.
[09-May-22 01:12:52] INFO - Finished server process [294438]
[09-May-22 01:12:52] INFO - Started server process [294499]
[09-May-22 01:12:52] INFO - Waiting for application startup.
[09-May-22 01:12:52] INFO - Application startup complete.
[09-May-22 01:13:29] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 119, in add_place
    result = session.query(salesmen).first(10)
TypeError: first() takes 1 positional argument but 2 were given
[09-May-22 01:13:41] INFO - Shutting down
[09-May-22 01:13:41] INFO - Waiting for application shutdown.
[09-May-22 01:13:41] INFO - Application shutdown complete.
[09-May-22 01:13:41] INFO - Finished server process [294499]
[09-May-22 01:13:41] INFO - Started server process [294602]
[09-May-22 01:13:41] INFO - Waiting for application startup.
[09-May-22 01:13:41] INFO - Application startup complete.
[09-May-22 01:14:54] INFO - Shutting down
[09-May-22 01:14:54] INFO - Waiting for application shutdown.
[09-May-22 01:14:54] INFO - Application shutdown complete.
[09-May-22 01:14:54] INFO - Finished server process [294602]
[09-May-22 01:14:54] INFO - Started server process [294665]
[09-May-22 01:14:54] INFO - Waiting for application startup.
[09-May-22 01:14:54] INFO - Application startup complete.
[09-May-22 01:15:15] INFO - Shutting down
[09-May-22 01:15:15] INFO - Waiting for application shutdown.
[09-May-22 01:15:15] INFO - Application shutdown complete.
[09-May-22 01:15:15] INFO - Finished server process [294665]
[09-May-22 01:15:15] INFO - Started server process [294733]
[09-May-22 01:15:15] INFO - Waiting for application startup.
[09-May-22 01:15:15] INFO - Application startup complete.
[09-May-22 01:15:37] INFO - Shutting down
[09-May-22 01:15:37] INFO - Waiting for application shutdown.
[09-May-22 01:15:37] INFO - Application shutdown complete.
[09-May-22 01:15:37] INFO - Finished server process [294733]
[09-May-22 01:15:37] INFO - Started server process [294780]
[09-May-22 01:15:37] INFO - Waiting for application startup.
[09-May-22 01:15:37] INFO - Application startup complete.
[09-May-22 01:15:40] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 124, in add_place
    return result.id_record
  File "/home/dr/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/dr/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 705, in get
    value = state._load_expired(state, passive)
  File "/home/dr/.local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/home/dr/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 911, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <salesmen at 0x7f44681d4280> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
[09-May-22 01:15:45] INFO - Shutting down
[09-May-22 01:15:45] INFO - Waiting for application shutdown.
[09-May-22 01:15:45] INFO - Application shutdown complete.
[09-May-22 01:15:45] INFO - Finished server process [294780]
[09-May-22 01:15:45] INFO - Started server process [294825]
[09-May-22 01:15:45] INFO - Waiting for application startup.
[09-May-22 01:15:45] INFO - Application startup complete.
[09-May-22 01:16:53] INFO - Shutting down
[09-May-22 01:16:54] INFO - Waiting for application shutdown.
[09-May-22 01:16:54] INFO - Application shutdown complete.
[09-May-22 01:16:54] INFO - Finished server process [294825]
[09-May-22 01:16:54] INFO - Started server process [294937]
[09-May-22 01:16:54] INFO - Waiting for application startup.
[09-May-22 01:16:54] INFO - Application startup complete.
[09-May-22 01:16:56] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 119, in add_place
    result = salesmen_row(session.query(salesmen).order_by(salesmen.id_record.desc()).first())
  File "pydantic/main.py", line 322, in pydantic.main.BaseModel.__init__
TypeError: __init__() takes exactly 1 positional argument (2 given)
[09-May-22 01:17:07] INFO - Shutting down
[09-May-22 01:17:07] INFO - Waiting for application shutdown.
[09-May-22 01:17:07] INFO - Application shutdown complete.
[09-May-22 01:17:07] INFO - Finished server process [294937]
[09-May-22 01:17:07] ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
    fairy._reset(pool)
  File "/home/dr/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 867, in _reset
    pool._dialect.do_rollback(self)
  File "/home/dr/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 502, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: terminating connection due to idle-in-transaction timeout
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[09-May-22 01:17:08] INFO - Started server process [294986]
[09-May-22 01:17:08] INFO - Waiting for application startup.
[09-May-22 01:17:08] INFO - Application startup complete.
[09-May-22 01:17:13] INFO - Shutting down
[09-May-22 01:17:13] INFO - Waiting for application shutdown.
[09-May-22 01:17:13] INFO - Application shutdown complete.
[09-May-22 01:17:13] INFO - Finished server process [294986]
[09-May-22 01:17:14] INFO - Started server process [295023]
[09-May-22 01:17:14] INFO - Waiting for application startup.
[09-May-22 01:17:14] INFO - Application startup complete.
[09-May-22 01:17:15] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 119, in add_place
    result = session.query(salesmen).order(salesmen.id_record.desc()).first()
AttributeError: 'Query' object has no attribute 'order'
[09-May-22 01:17:59] INFO - Shutting down
[09-May-22 01:17:59] INFO - Waiting for application shutdown.
[09-May-22 01:17:59] INFO - Application shutdown complete.
[09-May-22 01:17:59] INFO - Finished server process [295023]
[09-May-22 01:17:59] INFO - Started server process [295062]
[09-May-22 01:17:59] INFO - Waiting for application startup.
[09-May-22 01:17:59] INFO - Application startup complete.
[09-May-22 01:18:55] INFO - Shutting down
[09-May-22 01:18:56] INFO - Waiting for application shutdown.
[09-May-22 01:18:56] INFO - Application shutdown complete.
[09-May-22 01:18:56] INFO - Finished server process [295062]
[09-May-22 01:18:56] INFO - Started server process [295204]
[09-May-22 01:18:56] INFO - Waiting for application startup.
[09-May-22 01:18:56] INFO - Application startup complete.
[09-May-22 01:19:01] INFO - Shutting down
[09-May-22 01:19:01] INFO - Waiting for application shutdown.
[09-May-22 01:19:01] INFO - Application shutdown complete.
[09-May-22 01:19:01] INFO - Finished server process [295204]
[09-May-22 01:19:01] INFO - Started server process [295227]
[09-May-22 01:19:01] INFO - Waiting for application startup.
[09-May-22 01:19:01] INFO - Application startup complete.
[09-May-22 01:19:13] INFO - Shutting down
[09-May-22 01:19:13] INFO - Waiting for application shutdown.
[09-May-22 01:19:13] INFO - Application shutdown complete.
[09-May-22 01:19:13] INFO - Finished server process [295227]
[09-May-22 01:19:13] INFO - Started server process [295295]
[09-May-22 01:19:13] INFO - Waiting for application startup.
[09-May-22 01:19:13] INFO - Application startup complete.
[09-May-22 01:19:45] INFO - Started server process [295357]
[09-May-22 01:19:45] INFO - Waiting for application startup.
[09-May-22 01:19:45] INFO - Application startup complete.
[09-May-22 01:20:24] INFO - Shutting down
[09-May-22 01:20:24] INFO - Waiting for application shutdown.
[09-May-22 01:20:24] INFO - Application shutdown complete.
[09-May-22 01:20:24] INFO - Finished server process [295357]
[09-May-22 01:20:24] INFO - Started server process [295386]
[09-May-22 01:20:24] INFO - Waiting for application startup.
[09-May-22 01:20:24] INFO - Application startup complete.
[09-May-22 01:20:49] INFO - Shutting down
[09-May-22 01:20:49] INFO - Waiting for application shutdown.
[09-May-22 01:20:49] INFO - Application shutdown complete.
[09-May-22 01:20:49] INFO - Finished server process [295386]
[09-May-22 01:20:49] INFO - Started server process [295434]
[09-May-22 01:20:49] INFO - Waiting for application startup.
[09-May-22 01:20:49] INFO - Application startup complete.
[09-May-22 01:21:08] INFO - Shutting down
[09-May-22 01:21:08] INFO - Waiting for application shutdown.
[09-May-22 01:21:08] INFO - Application shutdown complete.
[09-May-22 01:21:08] INFO - Finished server process [295434]
[09-May-22 01:21:09] INFO - Started server process [295481]
[09-May-22 01:21:09] INFO - Waiting for application startup.
[09-May-22 01:21:09] INFO - Application startup complete.
[09-May-22 01:21:43] INFO - Shutting down
[09-May-22 01:21:43] INFO - Waiting for application shutdown.
[09-May-22 01:21:43] INFO - Application shutdown complete.
[09-May-22 01:21:43] INFO - Finished server process [295481]
[09-May-22 01:21:43] INFO - Started server process [295529]
[09-May-22 01:21:43] INFO - Waiting for application startup.
[09-May-22 01:21:43] INFO - Application startup complete.
[09-May-22 01:27:13] INFO - Shutting down
[09-May-22 01:27:13] INFO - Waiting for application shutdown.
[09-May-22 01:27:13] INFO - Application shutdown complete.
[09-May-22 01:27:13] INFO - Finished server process [295529]
[09-May-22 01:27:13] INFO - Started server process [295746]
[09-May-22 01:27:13] INFO - Waiting for application startup.
[09-May-22 01:27:13] INFO - Application startup complete.
[09-May-22 01:28:10] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 93, in delete_record
    result = session.query(salesmen).where( salesmen.id_record == data.id_record).delete()
AttributeError: 'Query' object has no attribute 'where'
[09-May-22 01:28:16] INFO - Shutting down
[09-May-22 01:28:16] INFO - Waiting for application shutdown.
[09-May-22 01:28:16] INFO - Application shutdown complete.
[09-May-22 01:28:16] INFO - Finished server process [295746]
[09-May-22 01:28:17] INFO - Started server process [295872]
[09-May-22 01:28:17] INFO - Waiting for application startup.
[09-May-22 01:28:17] INFO - Application startup complete.
[09-May-22 02:17:09] INFO - Shutting down
[09-May-22 02:17:09] INFO - Waiting for application shutdown.
[09-May-22 02:17:09] INFO - Application shutdown complete.
[09-May-22 02:17:09] INFO - Finished server process [295872]
[09-May-22 02:17:10] INFO - Started server process [296511]
[09-May-22 02:17:10] INFO - Waiting for application startup.
[09-May-22 02:17:10] INFO - Application startup complete.
[09-May-22 02:17:19] INFO - Shutting down
[09-May-22 02:17:19] INFO - Waiting for application shutdown.
[09-May-22 02:17:19] INFO - Application shutdown complete.
[09-May-22 02:17:19] INFO - Finished server process [296511]
[09-May-22 02:17:19] INFO - Started server process [296556]
[09-May-22 02:17:19] INFO - Waiting for application startup.
[09-May-22 02:17:19] INFO - Application startup complete.
[09-May-22 02:17:58] INFO - Shutting down
[09-May-22 02:17:58] INFO - Waiting for application shutdown.
[09-May-22 02:17:58] INFO - Application shutdown complete.
[09-May-22 02:17:58] INFO - Finished server process [296556]
[09-May-22 02:17:59] INFO - Started server process [296625]
[09-May-22 02:17:59] INFO - Waiting for application startup.
[09-May-22 02:17:59] INFO - Application startup complete.
[09-May-22 02:18:12] INFO - Shutting down
[09-May-22 02:18:12] INFO - Waiting for application shutdown.
[09-May-22 02:18:12] INFO - Application shutdown complete.
[09-May-22 02:18:12] INFO - Finished server process [296625]
[09-May-22 02:18:12] INFO - Started server process [296741]
[09-May-22 02:18:12] INFO - Waiting for application startup.
[09-May-22 02:18:12] INFO - Application startup complete.
[09-May-22 02:18:13] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 129, in add_place
    result = session.query(salesmen).filter(salesmen.id_player==data.id_player).order_by(salesmen.id_record.desc()).limit(10).all()
AttributeError: 'function' object has no attribute 'query'
[09-May-22 02:18:33] INFO - Shutting down
[09-May-22 02:18:34] INFO - Waiting for application shutdown.
[09-May-22 02:18:34] INFO - Application shutdown complete.
[09-May-22 02:18:34] INFO - Finished server process [296741]
[09-May-22 02:18:34] INFO - Started server process [296790]
[09-May-22 02:18:34] INFO - Waiting for application startup.
[09-May-22 02:18:34] INFO - Application startup complete.
[09-May-22 02:18:35] ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dr/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dr/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/dr/.local/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dr/hs_tracker/api_server/./main.py", line 129, in add_place
    result = session.query(salesmen).filter(salesmen.id_player==data.id_player).order_by(salesmen.id_record.desc()).limit(10).all()
NameError: name 'session' is not defined
[09-May-22 02:19:28] INFO - Shutting down
[09-May-22 02:19:28] INFO - Waiting for application shutdown.
